@extends('layouts.app')
@section('title', __('ui.imports'))
@section('content')
@include('partials.heading',['heading'=>__('ui.imports'),'description'=>__('ui.imports_description'),'eyebrow'=>'03 / '.__('ui.workspace')])
@if(isset($storage))
<section class="surface block storage-usage" aria-labelledby="storage-title">
    <div class="section-heading"><h2 id="storage-title">{{ __('ui.storage_usage') }}</h2><span id="storage-description" class="muted">{{ __('ui.storage_usage_detail', ['used'=>number_format($storage['bytes']/1048576,1,'.','’'), 'quota'=>number_format($storage['quota']/1048576,1,'.','’'), 'percent'=>number_format($storage['ratio']*100,1)]) }}</span></div>
    <meter min="0" max="1" low="0.8" high="0.95" optimum="0" value="{{ min(1,max(0,$storage['ratio'])) }}" aria-labelledby="storage-title" aria-describedby="storage-description"></meter>
    @if($storage['warning'])<p id="storage-warning" class="notice warning" role="status">{{ __('ui.storage_warning') }}</p>@endif
</section>
@endif
<ol class="steps"><li aria-current="step"><span>1</span>{{ __('ui.import_parameters') }}</li><li><span>2</span>{{ __('ui.dry_run') }}</li><li><span>3</span>{{ __('ui.application') }}</li></ol>
<section class="surface block"><h2>{{ __('ui.new_import') }}</h2><form class="section" method="post" action="{{ url('imports') }}" enctype="multipart/form-data">@csrf<div class="form-grid"><label class="field"><span>{{ __('ui.version') }}</span><select class="input" name="version_id" required>@foreach($versions as $version)<option value="{{ $version->id }}" @selected(old('version_id')==$version->id)>{{ $version->number }} · {{ __('ui.status_'.$version->status) }}</option>@endforeach</select></label><label class="field"><span>{{ __('ui.type') }}</span><select class="input" name="type" required>@foreach($types as $code=>$label)<option value="{{ $code }}" @selected(old('type')===$code)>{{ $label }}</option>@endforeach</select></label><label class="field"><span>{{ __('ui.source_kind') }}</span><select class="input" name="source_kind"><option value="publisher" @selected(old('source_kind')==='publisher')>{{ __('ui.publisher') }}</option><option value="organization" @selected(old('source_kind')==='organization')>{{ __('ui.organization_source') }}</option></select></label><label class="field"><span>{{ __('ui.organization') }}</span><select class="input" name="organization_id"><option value="">{{ __('ui.publisher') }}</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected(old('organization_id')==$organization->id)>{{ $organization->name }}</option>@endforeach</select></label></div><div class="upload section"><h3>{{ __('ui.choose_file') }}</h3><p class="field-hint">{{ __('ui.file_hint') }}</p><label for="devconf-file" class="sr-only">{{ __('ui.file') }}</label><input id="devconf-file" name="file" type="file" accept=".csv,.txt" required></div><div class="notice section">{{ __('ui.dry_run_help') }}</div><div class="form-actions"><button class="button primary" @disabled($versions->isEmpty())>{{ __('ui.analyze') }} →</button></div></form></section>
<section class="section"><div class="section-heading"><h2>{{ __('ui.import_history') }}</h2><a href="{{ url('publications') }}#versions" class="button small">{{ __('ui.new_version') }} +</a></div><div class="table-wrap"><table><thead><tr><th>{{ __('ui.file') }}</th><th>{{ __('ui.version') }}</th><th>{{ __('ui.type') }}</th><th>{{ __('ui.rows') }}</th><th>{{ __('ui.state') }}</th><th>{{ __('ui.author') }}</th><th>{{ __('ui.date') }}</th></tr></thead><tbody>@forelse($imports as $import)<tr><td><a href="{{ url('imports/'.$import->id) }}">{{ $import->filename }} →</a><span class="cell-caption">{{ $import->source_kind==='publisher'?__('ui.publisher'):$import->organization?->name }}</span></td><td>{{ $import->version?->number }}</td><td>{{ $types[$import->type] ?? $import->type }}</td><td>{{ number_format($import->row_count ?? 0, 0, '.', '’') }}</td><td>@include('partials.status',['status'=>$import->status])</td><td>{{ $import->author?->name }}</td><td>{{ $import->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</td></tr>@empty<tr><td colspan="7"><div class="empty-state"><h2>{{ __('ui.empty_title') }}</h2><p>{{ __('ui.file_hint') }}</p></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$imports])</section>
@endsection
