@extends('layouts.app')
@section('title', __('ui.import_report'))
@section('content')
<a href="{{ url('imports') }}" class="button quiet">← {{ __('ui.imports') }}</a><div class="section">@include('partials.heading',['heading'=>$import->filename,'description'=>__('ui.imports_description'),'headingContext'=>__('ui.imports').' / #'.$import->id])</div>
@php($processing = in_array($import->status,['queued','analyzing','apply_queued','applying']))
<ol class="steps"><li><span>1</span>{{ __('ui.import_parameters') }}</li><li @if(in_array($import->status,['queued','analyzing','analyzed'])) aria-current="step" @endif><span>2</span>{{ __('ui.dry_run') }}</li><li @if(in_array($import->status,['apply_queued','applying','applied'])) aria-current="step" @endif><span>3</span>{{ __('ui.application') }}</li></ol>
<div class="detail-grid"><section class="surface block"><div class="section-heading"><h2>{{ __('ui.import_report') }}</h2>@include('partials.status',['status'=>$import->status])</div>@if($processing)<div data-refresh-progress><progress aria-label="{{ __('ui.progress') }}" @if($import->progress ?? false) value="{{ $import->progress }}" max="100" @endif></progress><p class="progress-text">{{ __('ui.progress') }} : {{ $progress['rows'] ?? 0 }} / {{ $progress['total'] ?? 0 }} {{ __('ui.rows') }}. {{ __('ui.processing_help') }}</p></div>@endif
@if($import->error)<div class="notice error section" role="alert">{{ \App\Services\LocalizedMessage::display($import->error) }}</div>@endif
<table class="mini-table"><tbody>@foreach($import->report ?? [] as $key=>$value)@if(is_scalar($value) || $value===null)<tr><th>{{ __('ui.report_'.$key) === 'ui.report_'.$key ? str_replace('_',' ',$key) : __('ui.report_'.$key) }}</th><td>{{ is_bool($value) ? ($value ? __('ui.yes') : __('ui.no')) : (is_numeric($value) ? number_format($value, 0, '.', '’') : $value) }}</td></tr>@endif
@endforeach</tbody></table>
@foreach($import->report ?? [] as $key=>$value)@if(is_array($value) && count($value))<details class="section"><summary>{{ __('ui.report_'.$key) === 'ui.report_'.$key ? str_replace('_',' ',$key) : __('ui.report_'.$key) }}</summary><pre>{{ json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@endif
@endforeach
@if($import->status==='analyzed')<div class="notice section">{{ __('ui.dry_run_help') }}</div><div class="form-actions"><form action="{{ url('imports/'.$import->id.'/cancel') }}" method="post">@csrf<button class="button">{{ __('ui.cancel_import') }}</button></form><form action="{{ url('imports/'.$import->id.'/apply') }}" method="post" data-confirm="{{ __('ui.apply_confirm') }}">@csrf<input type="hidden" name="confirmed" value="1"><button class="button primary">{{ __('ui.apply_import') }} →</button></form></div>@endif
@if($import->status==='applied')<div class="form-actions"><a class="button primary" href="{{ url('terms') }}?version_id={{ $import->version_id }}&type={{ $import->type }}">{{ __('ui.translations') }} →</a></div>@endif
</section><section class="surface block"><h2>{{ __('ui.import_parameters') }}</h2><dl class="meta"><dt>{{ __('ui.version') }}</dt><dd>{{ $import->version?->number }}</dd><dt>{{ __('ui.type') }}</dt><dd>{{ $types[$import->type] ?? $import->type }}</dd><dt>{{ __('ui.organization') }}</dt><dd>{{ $import->source_kind==='publisher'?__('ui.publisher'):$import->organization?->name }}</dd><dt>{{ __('ui.rows') }}</dt><dd>{{ number_format($import->row_count ?? 0, 0, '.', '’') }}</dd><dt>{{ __('ui.format_version') }}</dt><dd>{{ $import->format_version ?? '1' }}</dd><dt>{{ __('ui.created_at') }}</dt><dd>{{ $import->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</dd><dt>{{ __('ui.created_by') }}</dt><dd>{{ $import->author?->name }}</dd><dt>{{ __('ui.updated_at') }}</dt><dd>{{ $import->updated_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</dd><dt>{{ __('ui.updated_by') }}</dt><dd>{{ $import->updated_by }}</dd><dt>{{ __('ui.checksum') }}</dt><dd><span class="key">{{ $import->sha256 }}</span></dd></dl>
@if($import->status==='applied' && ($canManage ?? false))<hr class="divider"><h3>{{ __('ui.initial_validation') }}</h3><p class="field-hint section">{{ __('ui.initial_preview_description') }}</p><form method="post" action="{{ route('imports.validation-preview.queue',$import) }}" class="section">@csrf<label class="field"><span>{{ __('ui.language') }}</span><select class="input" name="language">@foreach(['fr','it','en','de'] as $language)<option value="{{ $language }}">{{ __('ui.'.$language) }}</option>@endforeach</select></label><label class="check-label section"><input type="checkbox" name="override" value="1">{{ __('ui.manager_override') }}</label><div class="form-actions"><button class="button">{{ __('ui.initial_preview') }} →</button></div></form>@endif
</section></div>
<section class="surface block section"><div class="section-heading"><h2>{{ __('ui.import_rows') }}</h2><div class="row"><a class="button small" href="{{ route('imports.report',$import) }}">{{ __('ui.report') }} CSV ↓</a><a class="button small" href="{{ route('imports.original',$import) }}">{{ __('ui.import_original') }} ↓</a></div></div><form method="get" class="row"><label class="check-label"><input type="checkbox" name="collisions" value="1" @checked(request()->boolean('collisions'))>{{ __('ui.report_collision_rows') }}</label><button class="button small">{{ __('ui.filter') }}</button></form><div class="table-wrap"><table><thead><tr><th>{{ __('ui.rows') }}</th><th>{{ __('ui.key') }}</th><th>{{ __('ui.state') }}</th><th>{{ __('ui.report_collisions') }}</th></tr></thead><tbody>@foreach($rows as $row)<tr><td>{{ $row->record_number }}</td><td>@if($row->term_id)<a href="{{ url('terms/'.$row->term_id) }}">#{{ $row->term_id }} →</a>@else—@endif</td><td>{{ __('ui.report_'.$row->category) }}</td><td>{{ $row->collision ? __('ui.yes') : __('ui.no') }}</td></tr>@endforeach</tbody></table></div>@include('partials.pagination',['items'=>$rows])</section>
@include('imports.initial-operations')
@endsection
