<form method="get" action="{{ url()->current() }}" role="search" class="catalogue-filters">
<input type="hidden" name="language" value="{{ $language ?? request('language','fr') }}">
<div class="toolbar">
    <label class="field search"><span class="sr-only">{{ __('ui.search') }}</span><span class="search-control">@include('partials.icon', ['name' => 'search'])<input class="input" type="search" name="q" value="{{ request('q') }}" placeholder="{{ __('ui.search_hint') }}" aria-describedby="search-help"></span></label>
    <label class="field filter"><span class="sr-only">{{ __('ui.type') }}</span><select class="input" name="type"><option value="">{{ __('ui.all_types') }}</option>@foreach($types as $key=>$typeLabel)<option value="{{ $key }}" @selected(request('type')===$key)>{{ is_array($typeLabel) ? ($typeLabel['name'] ?? $key) : $typeLabel }}</option>@endforeach</select></label>
    <label class="field filter"><span class="sr-only">{{ __('ui.version') }}</span><select class="input" name="version_id"><option value="">{{ __('ui.all_versions') }}</option>@foreach($versions as $version)<option value="{{ $version->id }}" @selected(request('version_id')==$version->id)>{{ $version->number }}</option>@endforeach</select></label>
    @if(!($validationFilter ?? false))<label class="field filter"><span class="sr-only">{{ __('ui.state') }}</span><select class="input" name="state"><option value="">{{ __('ui.all_states') }}</option>@foreach(['missing','validated','published','review','obsolete','pending'] as $state)<option value="{{ $state }}" @selected(request('state')===$state)>{{ __('ui.status_'.$state) }}</option>@endforeach</select></label>@endif
    <button class="button primary" type="submit">{{ __('ui.filter') }}</button><a class="button quiet" href="{{ url()->current() }}?language={{ $language ?? 'fr' }}">{{ __('ui.reset') }}</a>
</div>
<details class="filters-more" @if(request()->hasAny(['scope','organization_id','context','sort'])) open @endif><summary>{{ __('ui.filters') }}</summary><div class="filters-grid">
    <label class="field"><span>{{ __('ui.scope') }}</span><select class="input" name="scope"><option value="">{{ __('ui.all') }}</option><option value="common" @selected(request('scope')==='common')>{{ __('ui.common') }}</option><option value="own" @selected(request('scope')==='own')>{{ __('ui.organization') }}</option></select></label>
    <label class="field"><span>{{ __('ui.organization') }}</span><select class="input" name="organization_id"><option value="">{{ __('ui.all_organizations') }}</option>@foreach($organizations ?? [] as $organization)<option value="{{ $organization->id }}" @selected(request('organization_id')==$organization->id)>{{ $organization->name }}</option>@endforeach</select></label>
    <label class="field"><span>{{ __('ui.context') }}</span><input class="input" name="context" value="{{ request('context') }}" placeholder="{{ __('ui.context_hint') }}"></label>
    <label class="field"><span>{{ __('ui.sort') }}</span><select class="input" name="sort"><option value="key" @selected(request('sort')==='key')>{{ __('ui.sort_key') }}</option><option value="updated" @selected(request('sort','updated')==='updated')>{{ __('ui.sort_recent') }}</option></select></label>
    <label class="field"><span>{{ __('ui.search_mode') }}</span><select class="input" name="search_mode"><option value="text" @selected(request('search_mode','text')==='text')>{{ __('ui.search_text') }}</option><option value="prefix" @selected(request('search_mode')==='prefix')>{{ __('ui.search_prefix') }}</option>@if($canManage ?? false)<option value="regex" @selected(request('search_mode')==='regex')>{{ __('ui.search_regex') }}</option>@endif</select></label>
    <label class="field"><span>{{ __('ui.results') }} / {{ __('ui.page') }}</span><select class="input" name="per_page">@foreach([25,50,100] as $pageSize)<option value="{{ $pageSize }}" @selected(request('per_page',25)==$pageSize)>{{ $pageSize }}</option>@endforeach @if($validationFilter ?? false)<option value="all" @selected(request('per_page')==='all')>{{ __('ui.all') }}</option>@endif</select></label>
</div><p id="search-help" class="field-hint section">{{ __('ui.search_help') }}</p></details>
</form>
