memory_limit=256M
upload_max_filesize=100M
post_max_size=110M
upload_tmp_dir=/var/www/html/storage/framework/uploads
max_input_time=1800
max_execution_time=120
expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
date.timezone=UTC
opcache.enable=1
opcache.validate_timestamps=0
