@extends('layouts.app')
@section('title', __('ui.publications'))
@section('content')
@include('partials.heading',['heading'=>__('ui.publications'),'description'=>__('ui.publications_description'),'eyebrow'=>'04 / '.__('ui.workspace')])
@if($canManage ?? false)
@php
    $selectedTypes = old('types', old('confirm') ? [] : array_keys($types ?? []));
    $selectedTypes = is_array($selectedTypes) ? $selectedTypes : [];
    $selectedVersion = old('version_id');
    $selectedVersion = is_scalar($selectedVersion) ? (string) $selectedVersion : '';
@endphp
<div class="detail-grid"><section class="surface block"><h2>{{ __('ui.new_publication') }}</h2><p class="field-hint section">{{ __('ui.publication_requirements') }}</p><form class="section" method="post" action="{{ route('publications.store') }}" data-confirm="{{ __('ui.publication_confirm') }}">@csrf<label class="field"><span>{{ __('ui.version') }}</span><select class="input" name="version_id" required>@foreach($versions as $version)<option value="{{ $version->id }}" @selected($selectedVersion === (string) $version->id)>{{ $version->number }} · {{ __('ui.status_'.$version->status) }}</option>@endforeach</select></label><div class="field section"><span>{{ __('ui.type') }}</span><div class="check-group">@foreach($types ?? [] as $code=>$label)<label class="check-label"><input type="checkbox" name="types[]" value="{{ $code }}" @checked(in_array($code, $selectedTypes, true))>{{ is_object($label) ? $label->label : $label }}</label>@endforeach</div></div><label class="field section"><span>{{ __('ui.publication_note') }}</span><textarea class="input" name="note" rows="3" maxlength="5000">{{ old('note') }}</textarea></label><input type="hidden" name="confirm" value="1"><p class="field-hint section">{{ __('ui.immutable_help') }}</p><div class="form-actions"><button class="button primary" @disabled($versions->isEmpty())>{{ __('ui.publish') }} →</button></div></form></section>
<section class="surface block" id="versions"><h2>{{ __('ui.new_version') }}</h2><form method="post" action="{{ route('versions.store') }}" class="section">@csrf<div class="form-stack"><label class="field"><span>{{ __('ui.version_number') }}</span><input class="input" name="number" placeholder="2026.2" required maxlength="60" value="{{ old('number') }}"></label><label class="field"><span>{{ __('ui.release_date') }}</span><input class="input" type="date" name="released_at" required value="{{ old('released_at') }}"></label><label class="field"><span>{{ __('ui.version_status') }}</span><select class="input" name="status">@foreach(['preparation','current','archived'] as $status)<option value="{{ $status }}">{{ __('ui.status_'.$status) }}</option>@endforeach</select></label></div><div class="form-actions"><button class="button">{{ __('ui.create_version') }} +</button></div></form></section></div>
@endif
<section class="section"><h2>{{ __('ui.publications') }}</h2><div class="table-wrap"><table><thead><tr><th>{{ __('ui.publication_number') }}</th><th>{{ __('ui.version') }}</th><th>{{ __('ui.note') }}</th><th>{{ __('ui.state') }}</th><th>{{ __('ui.author') }}</th><th>{{ __('ui.date') }}</th><th>{{ __('ui.actions') }}</th></tr></thead><tbody>@forelse($publications as $publication)<tr><td><a href="{{ route('publications.show',$publication) }}">{{ $publication->number }}</a></td><td>{{ $publication->version?->number }}</td><td>{{ $publication->note }}</td><td>@include('partials.status',['status'=>$publication->status])</td><td>{{ $publication->author?->name }}</td><td>{{ $publication->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</td><td><a class="button small" href="{{ route('publications.show',$publication) }}">{{ __('ui.open') }} →</a></td></tr>@empty<tr><td colspan="7"><div class="empty-state"><h2>{{ __('ui.empty_title') }}</h2><p>{{ __('ui.publications_description') }}</p></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$publications])</section>
<section class="surface block section"><h2>{{ __('ui.version') }}</h2><div class="table-wrap"><table><thead><tr><th>{{ __('ui.version_number') }}</th><th>{{ __('ui.release_date') }}</th><th>{{ __('ui.state') }}</th><th>{{ __('ui.actions') }}</th></tr></thead><tbody>@foreach($versions as $version)<tr><td>{{ $version->number }}</td><td>{{ $version->released_at ? \Illuminate\Support\Carbon::parse($version->released_at)->format('d.m.Y') : '—' }}</td><td>@include('partials.status',['status'=>$version->status])</td><td>@if($canManage ?? false)<form method="post" action="{{ route('versions.update',$version) }}" class="row">@csrf @method('PATCH')<input type="hidden" name="number" value="{{ $version->number }}"><input type="hidden" name="released_at" value="{{ $version->released_at ? \Illuminate\Support\Carbon::parse($version->released_at)->format('Y-m-d') : '' }}"><label class="sr-only" for="version-status-{{ $version->id }}">{{ __('ui.version_status') }}</label><select class="input" style="width:auto" id="version-status-{{ $version->id }}" name="status">@foreach(['preparation','current','archived'] as $status)<option value="{{ $status }}" @selected($version->status===$status)>{{ __('ui.status_'.$status) }}</option>@endforeach</select><button class="button small">{{ __('ui.save') }}</button></form>@endif @include('partials.trace',['entity'=>$version])</td></tr>@endforeach</tbody></table></div></section>
@endsection
