@extends('layouts.app')
@section('title', __('ui.publication_number').' '.$publication->number)
@section('content')
<a class="button quiet" href="{{ route('publications.index') }}">← {{ __('ui.publications') }}</a><div class="section">@include('partials.heading',['heading'=>$publication->number,'description'=>$publication->note,'headingContext'=>__('ui.publication_number').' / myABI '.$publication->version?->number])</div>
<div class="section-heading">@include('partials.status',['status'=>$publication->status])<span class="muted">{{ $publication->author?->name }} · {{ $publication->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</span></div>
@if(in_array($publication->status,['queued','building']))<div class="notice" data-refresh-progress><progress aria-label="{{ __('ui.progress') }}"></progress><p>{{ __('ui.processing_help') }}</p></div>@endif
@if($publication->error)<div class="notice error" role="alert">{{ \App\Services\LocalizedMessage::display($publication->error) }}</div>@endif
@if(($canManage ?? false) && $publication->status==='failed')<form method="post" action="{{ route('publications.retry',$publication) }}" data-confirm="{{ __('ui.confirm_action') }}" class="section">@csrf<input type="hidden" name="confirm" value="1"><button class="button">{{ __('ui.retry') }}</button></form>@endif
@if($publication->withdrawal_reason)<div class="notice error">{{ __('ui.status_withdrawn') }} : {{ $publication->withdrawal_reason }}</div>@endif
<div class="notice">{{ __('ui.immutable_help') }}</div>@include('partials.trace',['entity'=>$publication])
@foreach($downloads ?? [] as $organizationId=>$download)<section class="surface block section"><div class="section-heading"><div><p class="eyebrow">{{ __('ui.recipient') }}</p><h2>{{ $download['name'] }} <small>{{ $download['code'] }}</small></h2></div><a class="button primary" href="{{ route('publications.download',array_merge(['publication'=>$publication,'organization_id'=>$download['organization_id']],$publication->status==='withdrawn'?['withdrawn'=>1]:[])) }}">{{ __('ui.download') }} ↓</a></div><p class="muted">{{ __('ui.full_download') }}</p><dl class="meta"><dt>{{ __('ui.file') }}</dt><dd>{{ $download['archive']['name'] ?? '' }}</dd><dt>{{ __('ui.checksum') }}</dt><dd class="key">{{ $download['archive']['sha256'] ?? '' }}</dd></dl></section>@endforeach
@foreach($manifest['recipients'] ?? [] as $recipient)<section class="section"><h2>{{ __('ui.publication_files') }} · {{ $recipient['code'] }}</h2><div class="table-wrap"><table><thead><tr><th>{{ __('ui.file') }}</th><th>{{ __('ui.rows') }}</th><th>{{ __('ui.format_version') }}</th><th>{{ __('ui.coverage') }}</th><th>{{ __('ui.checksum') }}</th></tr></thead><tbody>@foreach($recipient['files'] ?? [] as $file)<tr><td>{{ $file['name'] }}</td><td>{{ number_format($file['records'], 0, '.', '’') }}</td><td>{{ $file['format_version'] }}</td><td>@foreach($file['coverage'] ?? [] as $language=>$coverage)<small>{{ strtoupper($language) }} · {{ number_format($coverage['validated'] ?? 0, 0, '.', '’') }} {{ __('ui.validated_count') }} / {{ number_format($coverage['fallback'] ?? 0, 0, '.', '’') }} {{ __('ui.fallback') }}</small><br>@endforeach</td><td><span class="key">{{ $file['sha256'] }}</span></td></tr>@endforeach</tbody></table></div></section>@endforeach
@if(($canManage ?? false) && in_array($publication->status,['ready','published']))<section class="surface block section"><details><summary>{{ __('ui.withdraw') }}</summary><form class="section" action="{{ route('publications.withdraw',$publication) }}" method="post" data-confirm="{{ __('ui.withdraw_confirm') }}">@csrf<input type="hidden" name="confirm" value="1"><label class="field"><span>{{ __('ui.reason') }}</span><textarea class="input" name="reason" required maxlength="2000"></textarea></label><div class="form-actions"><button class="button danger">{{ __('ui.withdraw') }}</button></div></form></details></section>@endif
@endsection
