@extends('layouts.app')
@section('title', __('ui.details'))
@section('content')
<a class="button quiet" href="{{ url('terms') }}?language={{ $language }}">← {{ __('ui.translations') }}</a>
<div class="section">@include('partials.heading', ['heading'=>($term->source_text !== null && $term->source_text !== '' ? $term->source_text : $term->label), 'eyebrow'=>($types[$term->type] ?? $term->type).' / '.__('ui.details')])</div>
@include('partials.languages')
@if($restoreRevision ?? null)<div class="notice">{{ __('ui.restored_from',['number'=>$restoreRevision->number]) }}</div>@endif
<div class="detail-grid"><section class="surface block"><div class="panel-label">{{ __('ui.key') }} <span>r{{ $term->revision_no }}</span></div><span class="key">{{ $term->label }}</span><dl class="meta"><dt>{{ __('ui.type') }}</dt><dd>{{ $types[$term->type] ?? $term->type }}</dd><dt>{{ __('ui.scope') }}</dt><dd>{{ $term->organization?->name ?? __('ui.common') }} @if($term->scope_unconfirmed)<span class="badge">{{ __('ui.scope_unconfirmed') }}</span>@endif</dd><dt>{{ __('ui.context') }}</dt><dd>{{ $term->context ?: '—' }}</dd><dt>{{ __('ui.revision') }}</dt><dd>{{ $term->revision_no }}</dd><dt>{{ __('ui.created_at') }}</dt><dd>{{ $term->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</dd><dt>{{ __('ui.updated_at') }}</dt><dd>{{ $term->updated_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</dd></dl>
@if($canManage ?? false)<hr class="divider"><form method="post" action="{{ url('terms/'.$term->id.'/scope') }}">@csrf<input type="hidden" name="lock_version" value="{{ $term->lock_version ?? 1 }}"><label class="field"><span>{{ __('ui.scope') }}</span><select class="input" name="organization_id"><option value="">{{ __('ui.common') }}</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected($term->organization_id===$organization->id)>{{ $organization->name }}</option>@endforeach</select></label><div class="form-actions"><button class="button small">{{ __('ui.save') }}</button></div></form>@endif
@include('partials.trace',['entity'=>$term])<hr class="divider"><h3>{{ __('ui.presence') }}</h3><div class="table-wrap"><table class="mini-table"><thead><tr><th>{{ __('ui.version') }}</th><th>{{ __('ui.imports') }}</th><th>{{ __('ui.date') }}</th></tr></thead><tbody>@foreach($presences as $presence)<tr><td>{{ $presence->version_number }}</td><td>@if($canManage ?? false)<a href="{{ url('imports/'.($presence->import_id ?? $presence->import_batch_id)) }}">#{{ $presence->import_id ?? $presence->import_batch_id }}</a>@else#{{ $presence->import_id ?? $presence->import_batch_id }}@endif</td><td>{{ \Illuminate\Support\Carbon::parse($presence->created_at)->timezone('Europe/Zurich')->format('d.m.Y') }}</td></tr>@endforeach</tbody></table></div>@include('partials.pagination',['items'=>$presences])
</section><div class="stack-gap">
@foreach($attributes as $attribute=>$values)
@php($current = data_get($term->validated, $attribute.'.'.$language))
@php($restoredInput = old('term_id')==$term->id && old('attribute')===$attribute && old('language')===$language && !old('proposal_id') && !old('supersedes_id') && \Illuminate\Support\Arr::has(session()->getOldInput(), 'value'))
@php($restoredValue = $restoredInput ? old('value','') : data_get($restoreRevision ?? null,'validated.'.$attribute.'.'.$language,''))
<section class="surface block" id="translation-{{ $loop->index }}"><div class="panel-label">{{ \Illuminate\Support\Facades\Lang::has('catalogue.attributes.'.$attribute) ? __('catalogue.attributes.'.$attribute) : $attribute }} <span>{{ $language }}</span></div><p class="source-text">{{ $values['reference'] ?? '' }}</p><hr class="divider"><div class="panel-label">{{ __('ui.current_value') }} @include('partials.status', ['status'=>data_get($term->review_needed,$attribute.'.'.$language) ? 'review' : ($current !== null ? 'validated' : 'missing')])</div><p class="translation-text">{{ $current ?? __('ui.no_translation') }}</p>
@if(data_get($term->review_needed,$attribute.'.'.$language) && auth()->user()->canValidate($language))<form action="{{ url('terms/'.$term->id.'/confirm') }}" method="post" class="section">@csrf<input type="hidden" name="term_id" value="{{ $term->id }}"><input type="hidden" name="attribute" value="{{ $attribute }}"><input type="hidden" name="language" value="{{ $language }}"><input type="hidden" name="lock_version" value="{{ $term->lock_version ?? 1 }}"><button class="button">{{ __('ui.confirm_value') }}</button></form>@endif
@php($placeholderCounts = \App\Domain\Devconf\TranslationValidator::placeholders($values['reference'] ?? ''))
@php($tokenMatches = [array_keys($placeholderCounts)])
@if($tokenMatches[0])<hr class="divider"><div class="panel-label">{{ __('ui.tokens') }}</div><div class="tokens">@foreach($tokenMatches[0] as $token)<span class="token">{{ $token }} ×{{ $placeholderCounts[$token] }}</span>@endforeach</div>@endif
@if(auth()->user()->canTranslate($language,$term->organization_id) && !$term->obsolete)<hr class="divider"><form action="{{ url('terms/'.$term->id.'/proposals') }}" method="post">@csrf<input type="hidden" name="term_id" value="{{ $term->id }}"><input type="hidden" name="attribute" value="{{ $attribute }}"><input type="hidden" name="language" value="{{ $language }}"><input type="hidden" name="lock_version" value="{{ $term->lock_version ?? 1 }}">@if($restoreRevision ?? null)<input type="hidden" name="restored_revision_id" value="{{ $restoreRevision->id }}">@endif
<x-proposal-editor :id="'new-proposal-'.$loop->index" :label="__('ui.new_proposal')" :value="$restoredValue" :restored="$restoredInput || (($restoreRevision ?? null) && $restoredValue !== '')" :source="$values['reference'] ?? ''" :hint="__('ui.proposal_hint').' '.__('ui.keyboard_hint')" /><div class="form-actions"><button class="button primary">{{ __('ui.propose') }} →</button></div></form>@endif
<details class="section"><summary>{{ __('ui.imported_values') }}</summary><div class="table-wrap"><table class="mini-table"><tbody>@foreach($values['translations'] ?? [] as $lang=>$value)<tr><th>{{ $lang }}</th><td class="preserve">{{ $value }}</td></tr>@endforeach</tbody></table></div></details>
</section>
@endforeach
</div></div>
<section class="surface block section" id="proposals"><div class="section-heading"><h2>{{ __('ui.proposals') }}</h2></div>
@forelse($proposals as $proposal)
<article class="section"><div class="panel-label"><span>{{ \Illuminate\Support\Facades\Lang::has('catalogue.attributes.'.$proposal->attribute) ? __('catalogue.attributes.'.$proposal->attribute) : $proposal->attribute }} · {{ $proposal->language }} · {{ $proposal->author?->name ?? __('ui.imports') }} · {{ $proposal->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</span>@include('partials.status',['status'=>$proposal->status])</div><p class="translation-text">{{ $proposal->value }}</p>@if($proposal->rejection_reason)<p class="client-error">{{ __('ui.reason') }} : {{ $proposal->rejection_reason }}</p>@endif
@if($proposal->anomalies)<div class="notice error section"><strong>{{ __('ui.blocking_anomalies') }}</strong><ul>@foreach($proposal->anomalies as $anomaly)<li>{{ \App\Domain\Devconf\TranslationValidator::displayMessage($anomaly) }}</li>@endforeach</ul></div>@endif
@if($proposal->status==='pending')
    @if(auth()->user()->canTranslate($proposal->language,$term->organization_id) && ($proposal->author_id===auth()->id() || ($proposal->import_id && !$proposal->claimed)))
    @php($restoredCorrection = old('proposal_id')==$proposal->id && \Illuminate\Support\Arr::has(session()->getOldInput(), 'value'))
    <details class="section" @if($restoredCorrection) open @endif><summary>{{ __('ui.correct') }}</summary><form method="post" action="{{ url('proposals/'.$proposal->id) }}" class="section">@csrf @method('PATCH')<input type="hidden" name="proposal_id" value="{{ $proposal->id }}"><input type="hidden" name="term_id" value="{{ $term->id }}"><input type="hidden" name="attribute" value="{{ $proposal->attribute }}"><input type="hidden" name="language" value="{{ $proposal->language }}"><input type="hidden" name="lock_version" value="{{ $proposal->lock_version }}"><x-proposal-editor :id="'correct-proposal-'.$proposal->id" :label="__('ui.proposal')" :value="$restoredCorrection ? old('value', $proposal->value) : $proposal->value" :restored="$restoredCorrection" :source="data_get($attributes,$proposal->attribute.'.reference','')" /><div class="form-actions"><button class="button">{{ __('ui.correct') }}</button></div></form></details>@endif
    @if(auth()->user()->canValidate($proposal->language))<form action="{{ url('proposals/'.$proposal->id.'/decide') }}" method="post" class="section">@csrf<input type="hidden" name="lock_version" value="{{ $proposal->lock_version }}"><div class="form-grid"><label class="field"><span>{{ __('ui.rejection_reason') }}</span><select class="input" name="reason_category"><option value="other">{{ __('ui.reject_other') }}</option>@foreach(['glossary','meaning','spelling','length','placeholder','superseded'] as $reason)<option value="{{ $reason }}">{{ __('ui.reject_'.$reason) }}</option>@endforeach</select></label><label class="field"><span>{{ __('ui.rejection_details') }}</span><input name="reason" class="input" maxlength="2000"></label></div><div class="form-actions">@if(($canManage ?? false) && $proposal->author_id===auth()->id())<label class="check-label"><input type="checkbox" name="override" value="1">{{ __('ui.manager_override') }}</label>@endif @if($proposal->author_id===auth()->id())<small class="muted">{{ __('ui.four_eyes') }}</small>@endif<button type="submit" class="button danger" name="decision" value="reject">{{ __('ui.reject') }}</button><button type="submit" class="button primary" name="decision" value="validate" @disabled($proposal->author_id===auth()->id() && !($canManage ?? false))>{{ __('ui.validate') }} ✓</button></div></form>@endif
@endif
@if($proposal->status==='rejected' && auth()->user()->canTranslate($proposal->language,$term->organization_id) && !$term->obsolete)
@php($restoredRejection = old('supersedes_id')==$proposal->id && \Illuminate\Support\Arr::has(session()->getOldInput(), 'value'))
<details class="section" @if($restoredRejection) open @endif><summary>{{ __('ui.correct_rejection') }}</summary><form method="post" action="{{ url('terms/'.$term->id.'/proposals') }}" class="section">@csrf<input type="hidden" name="term_id" value="{{ $term->id }}"><input type="hidden" name="supersedes_id" value="{{ $proposal->id }}"><input type="hidden" name="attribute" value="{{ $proposal->attribute }}"><input type="hidden" name="language" value="{{ $proposal->language }}"><input type="hidden" name="lock_version" value="{{ $term->lock_version }}"><x-proposal-editor :id="'replace-proposal-'.$proposal->id" :label="__('ui.new_proposal')" :value="$restoredRejection ? old('value', $proposal->value) : $proposal->value" :restored="$restoredRejection" :source="data_get($attributes,$proposal->attribute.'.reference','')" :hint="__('ui.proposal_hint')" /><div class="form-actions"><button class="button primary">{{ __('ui.propose') }} →</button></div></form></details>
@endif
@include('partials.trace',['entity'=>$proposal])<hr class="divider"></article>
@empty<p class="muted">{{ __('ui.no_proposal') }}</p>@endforelse
@include('partials.pagination',['items'=>$proposals])
</section>
<section class="surface block section"><h2>{{ __('ui.revisions') }}</h2><form method="get" action="{{ url()->current() }}" class="toolbar"><input type="hidden" name="language" value="{{ $language }}">@foreach(['from'=>__('ui.from_revision'),'to'=>__('ui.to_revision')] as $field=>$label)<label class="field filter"><span>{{ $label }}</span><select class="input" name="{{ $field }}">@foreach($revisions as $revision)<option value="{{ $revision->number ?? $revision->revision_no }}" @selected(request($field)==($revision->number ?? $revision->revision_no))>r{{ $revision->number ?? $revision->revision_no }} · {{ $revision->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i') }}</option>@endforeach</select></label>@endforeach<button class="button">{{ __('ui.compare') }}</button></form>
@if($comparison ?? null)@include('terms.comparison')@endif
<ol class="history">@forelse($revisions as $revision)<li><strong>r{{ $revision->number ?? $revision->revision_no }} · {{ $revision->origin ?? __('ui.revision') }}</strong><span>{{ $revision->author?->name ?? '—' }}</span><time>{{ $revision->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i:s') }}</time>@if(auth()->user()->canTranslate($language,$term->organization_id))<a class="button small section" href="{{ url()->current() }}?language={{ $language }}&restore_revision={{ $revision->number }}#translation-0">{{ __('ui.restore_revision') }}</a>@endif</li>@empty<li>{{ __('ui.no_history') }}</li>@endforelse</ol>@include('partials.pagination',['items'=>$revisions])</section>
@if(isset($sourceMetadata))<section class="surface block section"><details><summary>{{ __('ui.original_trace') }} / {{ __('ui.technical_attributes') }}</summary><div class="table-wrap"><table class="mini-table"><tbody>@foreach($sourceMetadata as $column=>$value)<tr><th>{{ $column }}</th><td class="preserve">{{ $value }}</td></tr>@endforeach</tbody></table></div></details></section>@endif
@if(isset($events))<section class="surface block section"><h2>{{ __('ui.history') }}</h2><ol class="history">@forelse($events as $event)<li><strong>@include('partials.event-label', ['value'=>$event->action])</strong><span>{{ $event->user?->name ?? $event->actor?->name ?? '—' }}</span><time>{{ $event->created_at?->copy()->timezone('Europe/Zurich')->format('d.m.Y H:i:s') }}</time></li>@empty<li>{{ __('ui.no_history') }}</li>@endforelse</ol></section>@endif
@endsection
