"""Opt-in disposable PHP/Nginx transport test; no application or business database is used.

MYABI_RUNTIME_APP_IMAGE must name a locally built myABI PHP 8.4 image. The current
PHP, FPM, entrypoint and Nginx configuration files are mounted read-only over it.
"""
from concurrent.futures import ThreadPoolExecutor
import hashlib
import http.client
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import time
import unittest
import uuid

ROOT = Path(__file__).resolve().parents[2]
APP_IMAGE = os.environ.get('MYABI_RUNTIME_APP_IMAGE')

PHP_PROBE = r'''<?php
header('Content-Type: application/json');
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { echo '{"healthy":true}'; exit; }
$file = $_FILES['upload'] ?? null;
if (!$file || $file['error'] !== UPLOAD_ERR_OK) {
    http_response_code(413); echo json_encode(['error' => $file['error'] ?? 'post_limit']); exit;
}
$handle = fopen($file['tmp_name'], 'rb');
if (fgetcsv($handle, 0, ';', '"', '') !== ['key', 'value']) { http_response_code(422); exit; }
$rows = 0;
while (($row = fgetcsv($handle, 0, ';', '"', '')) !== false) {
    if (count($row) !== 2) { http_response_code(422); exit; }
    $rows++;
}
fclose($handle);
$target = '/var/www/html/storage/app/private/'.bin2hex(random_bytes(8)).'.csv';
if (!move_uploaded_file($file['tmp_name'], $target)) { http_response_code(500); exit; }
echo json_encode(['bytes' => filesize($target), 'sha256' => hash_file('sha256', $target),
    'rows' => $rows, 'temporary_directory' => ini_get('upload_tmp_dir')]);
'''


@unittest.skipUnless(APP_IMAGE and shutil.which('docker'), 'Set MYABI_RUNTIME_APP_IMAGE for disposable Docker transport tests')
class DockerRuntimeTest(unittest.TestCase):
    def docker(self, *arguments):
        result = subprocess.run(['docker', *arguments], capture_output=True, text=True, timeout=90)
        if result.returncode:
            diagnostics = subprocess.run(['docker', 'logs', '--tail', '15', self.web], capture_output=True, text=True, timeout=10)
            self.fail(result.stderr + diagnostics.stderr)
        return result.stdout.strip()

    def setUp(self):
        self.prefix = 'myabi-audit-' + uuid.uuid4().hex[:12]
        self.network = self.prefix + '-network'
        self.volume = self.prefix + '-storage'
        self.php = self.prefix + '-php'
        self.web = self.prefix + '-web'
        self.blocker = self.prefix + '-old-address'
        self.temporary = tempfile.TemporaryDirectory(prefix='myabi-runtime-')
        self.addCleanup(self.temporary.cleanup)
        self.addCleanup(self.cleanup_docker)
        self.probe = Path(self.temporary.name) / 'index.php'
        self.probe.write_text(PHP_PROBE, encoding='utf-8')
        self.docker('network', 'create', self.network)
        self.docker('volume', 'create', self.volume)
        self.docker('run', '--rm', '--network', 'none', '--user', '0', '--entrypoint', 'sh',
                    '--mount', f'type=volume,source={self.volume},target=/storage', APP_IMAGE,
                    '-ec', 'chown 10001:10001 /storage; chmod 0770 /storage')
        self.start_php()
        self.docker('run', '-d', '--name', self.web, '--network', self.network,
                    '--publish', '127.0.0.1::8080', '-e', 'TRUSTED_PROXY_CIDR=127.0.0.1/32',
                    '-e', 'NGINX_ENVSUBST_FILTER=TRUSTED_PROXY_CIDR',
                    '--mount', f'type=bind,source={ROOT / "deploy/docker/nginx.conf.template"},target=/etc/nginx/templates/default.conf.template,readonly',
                    'nginx:1.30-alpine')
        self.port = int(self.docker('port', self.web, '8080').split(':')[-1])
        self.wait_http()
        self.docker('exec', self.web, 'nginx', '-t')

    def cleanup_docker(self):
        # Names are generated by this fixture; no existing project is selected.
        for name in [self.web, self.php, self.blocker]:
            subprocess.run(['docker', 'rm', '-f', name], capture_output=True, timeout=30)
        subprocess.run(['docker', 'volume', 'rm', self.volume], capture_output=True, timeout=30)
        subprocess.run(['docker', 'network', 'rm', self.network], capture_output=True, timeout=30)

    def start_php(self):
        self.docker('run', '-d', '--name', self.php, '--network', self.network,
                    '--network-alias', 'myabi-translate-php', '--user', '10001:10001', '--read-only',
                    '--tmpfs', '/tmp:rw,nosuid,nodev,size=64m,mode=1777',
                    '--tmpfs', '/var/www/html/bootstrap/cache:rw,nosuid,nodev,size=16m,uid=10001,gid=10001,mode=0770',
                    '--mount', f'type=volume,source={self.volume},target=/var/www/html/storage',
                    '--mount', f'type=bind,source={ROOT / "deploy/docker/php.ini"},target=/usr/local/etc/php/conf.d/zz-myabi.ini,readonly',
                    '--mount', f'type=bind,source={ROOT / "deploy/docker/php-fpm.conf"},target=/usr/local/etc/php-fpm.d/zz-myabi.conf,readonly',
                    '--mount', f'type=bind,source={ROOT / "deploy/docker/entrypoint.sh"},target=/probe-entrypoint.sh,readonly',
                    '--mount', f'type=bind,source={self.probe},target=/var/www/html/public/index.php,readonly',
                    '--entrypoint', 'sh', APP_IMAGE, '/probe-entrypoint.sh', 'php-fpm', '-F')

    def wait_http(self):
        for _ in range(40):
            connection = http.client.HTTPConnection('127.0.0.1', self.port, timeout=2)
            try:
                connection.request('GET', '/up')
                response = connection.getresponse()
                data = response.read()
                if response.status == 200 and json.loads(data).get('healthy'):
                    return
            except (OSError, http.client.HTTPException, ValueError):
                pass
            finally:
                connection.close()
            time.sleep(0.5)
        self.fail('PHP did not become reachable through Nginx')

    def sample(self, name, size):
        path = Path(self.temporary.name) / name
        line = b'synthetic;' + b'x' * 1013 + b'\n'
        with path.open('wb') as sample:
            sample.write(b'key;value\n')
            while sample.tell() + len(line) <= size:
                sample.write(line)
        return path

    def upload(self, path):
        boundary = 'myabiSyntheticBoundary'
        preamble = (f'--{boundary}\r\nContent-Disposition: form-data; name="upload"; filename="synthetic.csv"\r\n'
                    'Content-Type: text/csv\r\n\r\n').encode()
        end = f'\r\n--{boundary}--\r\n'.encode()
        connection = http.client.HTTPConnection('127.0.0.1', self.port, timeout=120)
        try:
            connection.putrequest('POST', '/upload')
            connection.putheader('Content-Type', 'multipart/form-data; boundary=' + boundary)
            connection.putheader('Content-Length', len(preamble) + path.stat().st_size + len(end))
            connection.endheaders()
            connection.send(preamble)
            digest = hashlib.sha256()
            with path.open('rb') as source:
                while chunk := source.read(1024 * 1024):
                    digest.update(chunk)
                    connection.send(chunk)
            connection.send(end)
            response = connection.getresponse()
            return response.status, json.loads(response.read()), digest.hexdigest()
        finally:
            connection.close()

    def assert_upload(self, path, response):
        status, data, digest = response
        self.assertEqual(200, status)
        self.assertEqual(path.stat().st_size, data['bytes'])
        self.assertEqual(digest, data['sha256'])
        self.assertGreater(data['rows'], 0)
        self.assertEqual('/var/www/html/storage/framework/uploads', data['temporary_directory'])

    def test_large_concurrent_uploads_and_php_address_replacement(self):
        small = self.sample('70m.csv', 70 * 1024**2)
        large = self.sample('100m.csv', 100 * 1024**2 - 1024)
        self.assert_upload(small, self.upload(small))
        self.assert_upload(large, self.upload(large))
        with ThreadPoolExecutor(max_workers=2) as pool:
            for response in pool.map(self.upload, [large, large]):
                self.assert_upload(large, response)
        too_large = self.sample('over-limit.csv', 101 * 1024**2)
        status, data, _ = self.upload(too_large)
        self.assertEqual(413, status)
        self.assertEqual(1, data['error'])  # UPLOAD_ERR_INI_SIZE
        leftovers = self.docker('exec', self.php, 'find', '/var/www/html/storage/framework/uploads', '-type', 'f')
        self.assertEqual('', leftovers)
        old_address = self.docker('inspect', '--format', '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}', self.php)
        self.docker('rm', '-f', self.php)
        self.docker('run', '-d', '--name', self.blocker, '--network', self.network, '--ip', old_address,
                    '--entrypoint', 'sleep', 'nginx:1.30-alpine', '120')
        self.start_php()
        new_address = self.docker('inspect', '--format', '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}', self.php)
        self.assertNotEqual(old_address, new_address)
        self.wait_http()  # Existing Nginx must resolve the new PHP IP without a reload.
        connection = http.client.HTTPConnection('127.0.0.1', self.port, timeout=10)
        try:
            connection.request('GET', '/login')
            response = connection.getresponse()
            self.assertEqual(200, response.status)
            self.assertTrue(json.loads(response.read())['healthy'])
        finally:
            connection.close()


if __name__ == '__main__':
    unittest.main()
